name: test-workflow
on: push
jobs:
  test-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Job Pass
        id: job-pass
        run: exit 0
      - name: Job fail
        id: job-fail
        run: exit 1
      - name: If Job
        if: success() || steps.job-pass.conclusion == 'failure'
        run: echo Hello
